/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automobiledealer.UI;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import static automobiledealer.UI.Driver.conn;
import static automobiledealer.UI.Driver.stmt;
import static automobiledealer.UI.Driver.rs;
import static automobiledealer.UI.Driver.loggedUser;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author AkbarFauzy
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */

    CardLayout cardLayout;
    JPanel prevMenuButton;
    public HomePage() {
        initComponents();
        cardLayout = (CardLayout)(ContentPanel.getLayout());
        prevMenuButton = Home_PanelButton;
        loggedUserLabel.setText("Hi, " + loggedUser.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        CustomerGender = new javax.swing.ButtonGroup();
        EmployeeGender = new javax.swing.ButtonGroup();
        EmployeePosition = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Home_PanelButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Employee_PanelButton = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Customer_PanelButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Vehicle_PanelButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Parts_PanelButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JLayeredPane();
        EmployeePageContentPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        AddEmployeeButton = new javax.swing.JButton();
        EmployeeFormPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        EmployeeForm_Label_username = new javax.swing.JLabel();
        EmployeeForm_TextInput_username = new javax.swing.JTextField();
        EmployeeForm_Label_password = new javax.swing.JLabel();
        EmployeeForm_TextInput_password = new javax.swing.JTextField();
        EmployeeForm_Button_add = new javax.swing.JButton();
        EmployeeForm_Label_gender = new javax.swing.JLabel();
        EmployeeForm_RB_Male = new javax.swing.JRadioButton();
        EmployeeForm_RB_Female = new javax.swing.JRadioButton();
        EmployeeForm_TextInput_confirmPassword = new javax.swing.JTextField();
        EmployeeForm_Label_confirmPassword = new javax.swing.JLabel();
        EmployeeForm_Label_name = new javax.swing.JLabel();
        EmployeeForm_TextInput_name = new javax.swing.JTextField();
        EmployeeForm_Label_position = new javax.swing.JLabel();
        EmployeeForm_RB_Manager = new javax.swing.JRadioButton();
        EmployeeForm_RB_Sales = new javax.swing.JRadioButton();
        EmployeeForm_RB_Technician = new javax.swing.JRadioButton();
        EmployeeForm_Label_birthdate = new javax.swing.JLabel();
        EmployeeForm_ComboBox_dd = new javax.swing.JComboBox<>();
        EmployeeForm_ComboBox_mm = new javax.swing.JComboBox<>();
        EmployeeForm_ComboBox_yyyy = new javax.swing.JComboBox<>();
        HomePageContentPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        CustomerPageContentPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        AddCustomerButton = new javax.swing.JButton();
        VehiclePageContentPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AddVehicleButton = new javax.swing.JButton();
        VehicleFormPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        VehicleForm_Label_price = new javax.swing.JLabel();
        VehicleForm_TextInput_name = new javax.swing.JTextField();
        VehicleForm_Label_brand = new javax.swing.JLabel();
        VehicleForm_TextInput_brand = new javax.swing.JTextField();
        VehicleForm_Label_color = new javax.swing.JLabel();
        VehicleForm_TextInput_color = new javax.swing.JTextField();
        VehicleForm_Button_add = new javax.swing.JButton();
        VehicleForm_Label_numWheels = new javax.swing.JLabel();
        VehicleForm_Label_numDoors = new javax.swing.JLabel();
        VehicleForm_Label_weight = new javax.swing.JLabel();
        VehicleForm_Spinner_numWheels = new javax.swing.JSpinner();
        VehicleForm_Spinner_numDoors = new javax.swing.JSpinner();
        VehicleForm_Spinner_numWeight = new javax.swing.JSpinner();
        VehicleForm_TextInput_transmition = new javax.swing.JTextField();
        VehicleForm_Label_name = new javax.swing.JLabel();
        VehicleForm_Label_transmition = new javax.swing.JLabel();
        VehicleForm_ComboBox_fueltype = new javax.swing.JComboBox<>();
        VehicleForm_Spinner_horsePower = new javax.swing.JSpinner();
        VehicleForm_Label_horsePower = new javax.swing.JLabel();
        VehicleForm_Label_fueltype = new javax.swing.JLabel();
        VehicleForm_Spinner_price = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        CustomerFormPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        CustomerForm_Label_name = new javax.swing.JLabel();
        CustomerForm_TextInput_name = new javax.swing.JTextField();
        CustomerForm_Label_address = new javax.swing.JLabel();
        CustomerForm_TextInput_address = new javax.swing.JTextField();
        CustomerForm_Label_phoneNumber = new javax.swing.JLabel();
        CustomerForm_TextInput_phoneNumber = new javax.swing.JTextField();
        CustomerForm_Button_add = new javax.swing.JButton();
        CustomerForm_Label_gender = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CustomerForm_RB_Male = new javax.swing.JRadioButton();
        CustomerForm_RB_Female = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loggedUserLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("App Name");

        Home_PanelButton.setBackground(new java.awt.Color(0, 90, 192));
        Home_PanelButton.setForeground(new java.awt.Color(255, 255, 255));
        Home_PanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_PanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home_PanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Home_PanelButtonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");

        javax.swing.GroupLayout Home_PanelButtonLayout = new javax.swing.GroupLayout(Home_PanelButton);
        Home_PanelButton.setLayout(Home_PanelButtonLayout);
        Home_PanelButtonLayout.setHorizontalGroup(
            Home_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_PanelButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        Home_PanelButtonLayout.setVerticalGroup(
            Home_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_PanelButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Employee_PanelButton.setBackground(new java.awt.Color(255, 255, 255));
        Employee_PanelButton.setForeground(new java.awt.Color(255, 255, 255));
        Employee_PanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employee_PanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Employee_PanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Employee_PanelButtonMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Employee");

        javax.swing.GroupLayout Employee_PanelButtonLayout = new javax.swing.GroupLayout(Employee_PanelButton);
        Employee_PanelButton.setLayout(Employee_PanelButtonLayout);
        Employee_PanelButtonLayout.setHorizontalGroup(
            Employee_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_PanelButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        Employee_PanelButtonLayout.setVerticalGroup(
            Employee_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_PanelButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Customer_PanelButton.setBackground(new java.awt.Color(255, 255, 255));
        Customer_PanelButton.setForeground(new java.awt.Color(255, 255, 255));
        Customer_PanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customer_PanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Customer_PanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Customer_PanelButtonMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer");

        javax.swing.GroupLayout Customer_PanelButtonLayout = new javax.swing.GroupLayout(Customer_PanelButton);
        Customer_PanelButton.setLayout(Customer_PanelButtonLayout);
        Customer_PanelButtonLayout.setHorizontalGroup(
            Customer_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Customer_PanelButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        Customer_PanelButtonLayout.setVerticalGroup(
            Customer_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Customer_PanelButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Vehicle_PanelButton.setBackground(new java.awt.Color(255, 255, 255));
        Vehicle_PanelButton.setForeground(new java.awt.Color(255, 255, 255));
        Vehicle_PanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vehicle_PanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Vehicle_PanelButtonMouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Vehicle");

        javax.swing.GroupLayout Vehicle_PanelButtonLayout = new javax.swing.GroupLayout(Vehicle_PanelButton);
        Vehicle_PanelButton.setLayout(Vehicle_PanelButtonLayout);
        Vehicle_PanelButtonLayout.setHorizontalGroup(
            Vehicle_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vehicle_PanelButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Vehicle_PanelButtonLayout.setVerticalGroup(
            Vehicle_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vehicle_PanelButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Parts_PanelButton.setBackground(new java.awt.Color(255, 255, 255));
        Parts_PanelButton.setForeground(new java.awt.Color(255, 255, 255));
        Parts_PanelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Parts_PanelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Parts_PanelButtonMouseEntered(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Parts");

        javax.swing.GroupLayout Parts_PanelButtonLayout = new javax.swing.GroupLayout(Parts_PanelButton);
        Parts_PanelButton.setLayout(Parts_PanelButtonLayout);
        Parts_PanelButtonLayout.setHorizontalGroup(
            Parts_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Parts_PanelButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Parts_PanelButtonLayout.setVerticalGroup(
            Parts_PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Parts_PanelButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(Home_PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Customer_PanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parts_PanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vehicle_PanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Employee_PanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(Home_PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Employee_PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Customer_PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Vehicle_PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Parts_PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Home_PanelButton.getAccessibleContext().setAccessibleName("HomePanelButton");
        Customer_PanelButton.getAccessibleContext().setAccessibleName("CustomerPanelButton");
        Vehicle_PanelButton.getAccessibleContext().setAccessibleName("VehiclePanelButton");

        ContentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ContentPanel.setLayout(new java.awt.CardLayout());

        EmployeePageContentPanel.setBackground(new java.awt.Color(246, 249, 255));

        jLabel14.setBackground(new java.awt.Color(0, 90, 192));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 90, 192));
        jLabel14.setText("Employee");

        AddEmployeeButton.setText("Add Employee");
        AddEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeePageContentPanelLayout = new javax.swing.GroupLayout(EmployeePageContentPanel);
        EmployeePageContentPanel.setLayout(EmployeePageContentPanelLayout);
        EmployeePageContentPanelLayout.setHorizontalGroup(
            EmployeePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePageContentPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                .addComponent(AddEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        EmployeePageContentPanelLayout.setVerticalGroup(
            EmployeePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePageContentPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(EmployeePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AddEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(520, Short.MAX_VALUE))
        );

        ContentPanel.add(EmployeePageContentPanel, "EmployeePageContentPanel");

        EmployeeFormPanel.setBackground(new java.awt.Color(246, 249, 255));

        jLabel16.setBackground(new java.awt.Color(0, 90, 192));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 90, 192));
        jLabel16.setText("Employee Form");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        EmployeeForm_Label_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeForm_Label_username.setText("Username");

        EmployeeForm_TextInput_username.setToolTipText("");

        EmployeeForm_Label_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeForm_Label_password.setText("Password");

        EmployeeForm_TextInput_password.setToolTipText("");

        EmployeeForm_Button_add.setText("Add");
        EmployeeForm_Button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeForm_Button_addActionPerformed(evt);
            }
        });

        EmployeeForm_Label_gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeForm_Label_gender.setText("Gender");

        EmployeeGender.add(EmployeeForm_RB_Male);
        EmployeeForm_RB_Male.setText("Male");

        EmployeeGender.add(EmployeeForm_RB_Female);
        EmployeeForm_RB_Female.setText("Female");

        EmployeeForm_TextInput_confirmPassword.setToolTipText("");

        EmployeeForm_Label_confirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeForm_Label_confirmPassword.setText("Confirm Password");

        EmployeeForm_Label_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeForm_Label_name.setText("Full Name");

        EmployeeForm_TextInput_name.setToolTipText("");

        EmployeeForm_Label_position.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeForm_Label_position.setText("Position");

        EmployeePosition.add(EmployeeForm_RB_Manager);
        EmployeeForm_RB_Manager.setText("Manager");

        EmployeePosition.add(EmployeeForm_RB_Sales);
        EmployeeForm_RB_Sales.setText("Sales");

        EmployeePosition.add(EmployeeForm_RB_Technician);
        EmployeeForm_RB_Technician.setText("Technician");

        EmployeeForm_Label_birthdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeForm_Label_birthdate.setText("Date of Birth");

        EmployeeForm_ComboBox_dd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EmployeeForm_ComboBox_mm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EmployeeForm_ComboBox_yyyy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeForm_Label_confirmPassword)
                            .addComponent(EmployeeForm_TextInput_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(262, 395, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeForm_Label_username)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmployeeForm_Label_password)
                                .addComponent(EmployeeForm_TextInput_password, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addComponent(EmployeeForm_TextInput_username))
                            .addComponent(EmployeeForm_Label_name)
                            .addComponent(EmployeeForm_TextInput_name, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeForm_Label_position)
                            .addComponent(EmployeeForm_Label_gender)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployeeForm_RB_Manager, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmployeeForm_RB_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployeeForm_RB_Female, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(EmployeeForm_RB_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(EmployeeForm_RB_Technician, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(EmployeeForm_Label_birthdate)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(EmployeeForm_ComboBox_dd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(EmployeeForm_ComboBox_yyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(EmployeeForm_ComboBox_mm, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmployeeForm_Button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(EmployeeForm_Label_username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmployeeForm_TextInput_username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmployeeForm_Label_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmployeeForm_TextInput_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmployeeForm_Label_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeForm_TextInput_password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(EmployeeForm_Label_gender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployeeForm_RB_Male, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeForm_RB_Female, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(EmployeeForm_Label_position))
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EmployeeForm_RB_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EmployeeForm_RB_Manager, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(EmployeeForm_RB_Technician, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(EmployeeForm_Label_birthdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployeeForm_ComboBox_dd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeForm_ComboBox_mm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeForm_ComboBox_yyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeForm_Label_confirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeForm_TextInput_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeForm_Button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        EmployeeForm_RB_Male.setActionCommand("Male");
        EmployeeForm_RB_Female.setActionCommand("Female");
        EmployeeForm_RB_Manager.setActionCommand("Manager");
        EmployeeForm_RB_Sales.setActionCommand("Sales");
        EmployeeForm_RB_Technician.setActionCommand("Tech");

        javax.swing.GroupLayout EmployeeFormPanelLayout = new javax.swing.GroupLayout(EmployeeFormPanel);
        EmployeeFormPanel.setLayout(EmployeeFormPanelLayout);
        EmployeeFormPanelLayout.setHorizontalGroup(
            EmployeeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeFormPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(EmployeeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        EmployeeFormPanelLayout.setVerticalGroup(
            EmployeeFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeFormPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        ContentPanel.add(EmployeeFormPanel, "EmployeeFormPanel");

        HomePageContentPanel.setBackground(new java.awt.Color(246, 249, 255));
        HomePageContentPanel.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(0, 90, 192));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 90, 192));
        jLabel7.setText("HOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HomePageContentPanelLayout = new javax.swing.GroupLayout(HomePageContentPanel);
        HomePageContentPanel.setLayout(HomePageContentPanelLayout);
        HomePageContentPanelLayout.setHorizontalGroup(
            HomePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageContentPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(HomePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        HomePageContentPanelLayout.setVerticalGroup(
            HomePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageContentPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        ContentPanel.add(HomePageContentPanel, "HomePageContentPanel");

        CustomerPageContentPanel.setBackground(new java.awt.Color(246, 249, 255));

        jLabel8.setBackground(new java.awt.Color(0, 90, 192));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 90, 192));
        jLabel8.setText("CUSTOMER");

        AddCustomerButton.setText("Add Customer");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerPageContentPanelLayout = new javax.swing.GroupLayout(CustomerPageContentPanel);
        CustomerPageContentPanel.setLayout(CustomerPageContentPanelLayout);
        CustomerPageContentPanelLayout.setHorizontalGroup(
            CustomerPageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPageContentPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(AddCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        CustomerPageContentPanelLayout.setVerticalGroup(
            CustomerPageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPageContentPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(CustomerPageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AddCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(520, Short.MAX_VALUE))
        );

        ContentPanel.add(CustomerPageContentPanel, "CustomerPageContentPanel");

        VehiclePageContentPanel.setBackground(new java.awt.Color(246, 249, 255));

        jLabel11.setBackground(new java.awt.Color(0, 90, 192));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 90, 192));
        jLabel11.setText("VEHICLE");

        AddVehicleButton.setText("Add Vehicle");
        AddVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVehicleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VehiclePageContentPanelLayout = new javax.swing.GroupLayout(VehiclePageContentPanel);
        VehiclePageContentPanel.setLayout(VehiclePageContentPanelLayout);
        VehiclePageContentPanelLayout.setHorizontalGroup(
            VehiclePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclePageContentPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, Short.MAX_VALUE)
                .addComponent(AddVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        VehiclePageContentPanelLayout.setVerticalGroup(
            VehiclePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiclePageContentPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(VehiclePageContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AddVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(520, Short.MAX_VALUE))
        );

        ContentPanel.add(VehiclePageContentPanel, "VehiclePageContentPanel");

        VehicleFormPanel.setBackground(new java.awt.Color(246, 249, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        VehicleForm_Label_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_price.setText("Price");

        VehicleForm_TextInput_name.setToolTipText("");

        VehicleForm_Label_brand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_brand.setText("Brand");

        VehicleForm_TextInput_brand.setToolTipText("");

        VehicleForm_Label_color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_color.setText("Color");

        VehicleForm_TextInput_color.setToolTipText("");

        VehicleForm_Button_add.setText("Add");
        VehicleForm_Button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleForm_Button_addActionPerformed(evt);
            }
        });

        VehicleForm_Label_numWheels.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_numWheels.setText("Number of Wheels");

        VehicleForm_Label_numDoors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_numDoors.setText("Number of Doors");

        VehicleForm_Label_weight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_weight.setText("Weight");

        VehicleForm_Spinner_numWheels.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VehicleForm_Spinner_numWheels.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        VehicleForm_Spinner_numDoors.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VehicleForm_Spinner_numDoors.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        VehicleForm_Spinner_numWeight.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VehicleForm_Spinner_numWeight.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        VehicleForm_TextInput_transmition.setToolTipText("");

        VehicleForm_Label_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_name.setText("Name");

        VehicleForm_Label_transmition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_transmition.setText("Transmition");

        VehicleForm_ComboBox_fueltype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        VehicleForm_Spinner_horsePower.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VehicleForm_Spinner_horsePower.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        VehicleForm_Label_horsePower.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_horsePower.setText("Horse Power");

        VehicleForm_Label_fueltype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VehicleForm_Label_fueltype.setText("FuelType");

        VehicleForm_Spinner_price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        VehicleForm_Spinner_price.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VehicleForm_Label_brand)
                    .addComponent(VehicleForm_Label_color)
                    .addComponent(VehicleForm_TextInput_color, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(VehicleForm_TextInput_brand)
                    .addComponent(VehicleForm_TextInput_name)
                    .addComponent(VehicleForm_Label_weight)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VehicleForm_Spinner_numWheels, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VehicleForm_Label_numWheels, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VehicleForm_Label_numDoors, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VehicleForm_Spinner_numDoors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(VehicleForm_Spinner_numWeight)
                    .addComponent(VehicleForm_Label_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(VehicleForm_TextInput_transmition, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VehicleForm_Button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(VehicleForm_Label_transmition)
                                .addComponent(VehicleForm_Label_price)
                                .addComponent(VehicleForm_ComboBox_fueltype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(VehicleForm_Spinner_horsePower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(VehicleForm_Label_horsePower)
                                .addComponent(VehicleForm_Label_fueltype)
                                .addComponent(VehicleForm_Spinner_price)))
                        .addContainerGap())))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_Label_transmition)
                    .addComponent(VehicleForm_Label_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_TextInput_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleForm_TextInput_transmition, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_Label_price)
                    .addComponent(VehicleForm_Label_brand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_TextInput_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleForm_Spinner_price, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_Label_fueltype)
                    .addComponent(VehicleForm_Label_color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_TextInput_color, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleForm_ComboBox_fueltype, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_Label_numWheels)
                    .addComponent(VehicleForm_Label_numDoors)
                    .addComponent(VehicleForm_Label_horsePower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_Spinner_numWheels, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleForm_Spinner_numDoors, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleForm_Spinner_horsePower, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(VehicleForm_Label_weight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehicleForm_Spinner_numWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleForm_Button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jLabel15.setBackground(new java.awt.Color(0, 90, 192));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 90, 192));
        jLabel15.setText("Vehicle Form");

        javax.swing.GroupLayout VehicleFormPanelLayout = new javax.swing.GroupLayout(VehicleFormPanel);
        VehicleFormPanel.setLayout(VehicleFormPanelLayout);
        VehicleFormPanelLayout.setHorizontalGroup(
            VehicleFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleFormPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VehicleFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(625, 625, 625))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleFormPanelLayout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        VehicleFormPanelLayout.setVerticalGroup(
            VehicleFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleFormPanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        ContentPanel.add(VehicleFormPanel, "VehicleFormPanel");

        CustomerFormPanel.setBackground(new java.awt.Color(246, 249, 255));
        CustomerFormPanel.setToolTipText("");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        CustomerForm_Label_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerForm_Label_name.setText("Name");

        CustomerForm_TextInput_name.setToolTipText("");

        CustomerForm_Label_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerForm_Label_address.setText("Address");

        CustomerForm_TextInput_address.setToolTipText("");

        CustomerForm_Label_phoneNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerForm_Label_phoneNumber.setText("Phone Number");

        CustomerForm_TextInput_phoneNumber.setToolTipText("");

        CustomerForm_Button_add.setText("Add");
        CustomerForm_Button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerForm_Button_addActionPerformed(evt);
            }
        });

        CustomerForm_Label_gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerForm_Label_gender.setText("Gender");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automobiledealer/UI/costumer@2x 1.png"))); // NOI18N

        CustomerGender.add(CustomerForm_RB_Male);
        CustomerForm_RB_Male.setText("Male");

        CustomerGender.add(CustomerForm_RB_Female);
        CustomerForm_RB_Female.setText("Female");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(CustomerForm_Button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CustomerForm_Label_name)
                                .addComponent(CustomerForm_Label_address)
                                .addComponent(CustomerForm_Label_phoneNumber)
                                .addComponent(CustomerForm_Label_gender)
                                .addComponent(CustomerForm_TextInput_phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addComponent(CustomerForm_TextInput_address)
                                .addComponent(CustomerForm_TextInput_name))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(CustomerForm_RB_Male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CustomerForm_RB_Female)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(109, 109, 109))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(CustomerForm_Label_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerForm_TextInput_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerForm_Label_address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerForm_TextInput_address, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerForm_Label_phoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerForm_TextInput_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerForm_Label_gender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerForm_RB_Male)
                            .addComponent(CustomerForm_RB_Female))))
                .addGap(23, 23, 23)
                .addComponent(CustomerForm_Button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel10.setBackground(new java.awt.Color(0, 90, 192));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 90, 192));
        jLabel10.setText("Add Customer");

        javax.swing.GroupLayout CustomerFormPanelLayout = new javax.swing.GroupLayout(CustomerFormPanel);
        CustomerFormPanel.setLayout(CustomerFormPanelLayout);
        CustomerFormPanelLayout.setHorizontalGroup(
            CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerFormPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        CustomerFormPanelLayout.setVerticalGroup(
            CustomerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerFormPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        ContentPanel.add(CustomerFormPanel, "CustomerFormPanel");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        loggedUserLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loggedUserLabel.setForeground(new java.awt.Color(0, 90, 192));
        loggedUserLabel.setText("Hi, Jonh Doe");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automobiledealer/UI/profile@2x 1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loggedUserLabel)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(loggedUserLabel)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        loggedUserLabel.getAccessibleContext().setAccessibleName("nameLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed
        cardLayout.show(ContentPanel, "CustomerFormPanel");
    }//GEN-LAST:event_AddCustomerButtonActionPerformed

    private void AddVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVehicleButtonActionPerformed
       cardLayout.show(ContentPanel, "VehicleFormPanel");
    }//GEN-LAST:event_AddVehicleButtonActionPerformed

    private void Parts_PanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Parts_PanelButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Parts_PanelButtonMouseEntered

    private void Parts_PanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Parts_PanelButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Parts_PanelButtonMouseClicked

    private void Vehicle_PanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vehicle_PanelButtonMouseEntered
        if (prevMenuButton != Vehicle_PanelButton){
            Vehicle_PanelButton.setBackground(new Color(246,249,255));
        }
    }//GEN-LAST:event_Vehicle_PanelButtonMouseEntered

    private void Vehicle_PanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vehicle_PanelButtonMouseClicked
        cardLayout.show(ContentPanel, "VehiclePageContentPanel");
        Vehicle_PanelButton.setBackground(new Color(0,90,192));
        Vehicle_PanelButton.getComponent(0).setForeground(Color.WHITE);
        prevMenuButton.setBackground(new Color(255,255,255));
        prevMenuButton.getComponent(0).setForeground(Color.BLACK);
        prevMenuButton = Vehicle_PanelButton;
    }//GEN-LAST:event_Vehicle_PanelButtonMouseClicked

    private void Customer_PanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_PanelButtonMouseExited
        if(prevMenuButton != Customer_PanelButton){
            Customer_PanelButton.setBackground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Customer_PanelButtonMouseExited

    private void Customer_PanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_PanelButtonMouseEntered
        if (prevMenuButton != Customer_PanelButton){
            Customer_PanelButton.setBackground(new Color(246,249,255));
        }
    }//GEN-LAST:event_Customer_PanelButtonMouseEntered

    private void Customer_PanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_PanelButtonMouseClicked
        cardLayout.show(ContentPanel, "CustomerPageContentPanel");
        Customer_PanelButton.setBackground(new Color(0,90,192));
        Customer_PanelButton.getComponent(0).setForeground(Color.WHITE);
        prevMenuButton.setBackground(new Color(255,255,255));
        prevMenuButton.getComponent(0).setForeground(Color.BLACK);
        prevMenuButton = Customer_PanelButton;
    }//GEN-LAST:event_Customer_PanelButtonMouseClicked

    private void Employee_PanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_PanelButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_PanelButtonMouseExited

    private void Employee_PanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_PanelButtonMouseEntered
        cardLayout.show(ContentPanel, "EmployeePageContentPanel");
        Employee_PanelButton.setBackground(new Color(0,90,192));
        Employee_PanelButton.getComponent(0).setForeground(Color.WHITE);
        prevMenuButton.setBackground(new Color(255,255,255));
        prevMenuButton.getComponent(0).setForeground(Color.BLACK);
        prevMenuButton = Employee_PanelButton;
    }//GEN-LAST:event_Employee_PanelButtonMouseEntered

    private void Employee_PanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_PanelButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_PanelButtonMouseClicked

    private void Home_PanelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_PanelButtonMouseExited
        if (prevMenuButton != Home_PanelButton){
            Home_PanelButton.setBackground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Home_PanelButtonMouseExited

    private void Home_PanelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_PanelButtonMouseEntered
        if (prevMenuButton != Home_PanelButton){
            Home_PanelButton.setBackground(new Color(246,249,255));
        }
    }//GEN-LAST:event_Home_PanelButtonMouseEntered

    private void Home_PanelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_PanelButtonMouseClicked
        cardLayout.show(ContentPanel, "HomePageContentPanel");
        Home_PanelButton.setBackground(new Color(0,90,192));
        Home_PanelButton.getComponent(0).setForeground(Color.WHITE);
        prevMenuButton.setBackground(new Color(255,255,255));
        prevMenuButton.getComponent(0).setForeground(Color.BLACK);
        prevMenuButton = Home_PanelButton;
    }//GEN-LAST:event_Home_PanelButtonMouseClicked

    private void CustomerForm_Button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerForm_Button_addActionPerformed
        try{
            stmt = conn.prepareStatement("INSERT INTO customer(name,address,phone_number,gender) VALUES(?,?,?,?)");
            stmt.setString(1,CustomerForm_TextInput_name.getText());
            stmt.setString(2,CustomerForm_TextInput_address.getText());
            stmt.setString(3,CustomerForm_TextInput_phoneNumber.getText());
            stmt.setString(4,CustomerGender.getSelection().getActionCommand());
            stmt.execute();
            stmt.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Dialog", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CustomerForm_Button_addActionPerformed

    private void AddEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeButtonActionPerformed
        cardLayout.show(ContentPanel, "EmployeeFormPanel");
    }//GEN-LAST:event_AddEmployeeButtonActionPerformed

    private void VehicleForm_Button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleForm_Button_addActionPerformed
        try{
            stmt = conn.prepareStatement("INSERT INTO "
                    + "vehicle(name, brand, color, number_wheel, number_doors, transmission, price, fuel_type, horse_power, model, load_capacity) "
                    + "VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            stmt.setString(1, VehicleForm_TextInput_name.getText());
            stmt.setString(2, VehicleForm_TextInput_brand.getText());
            stmt.setString(3, VehicleForm_TextInput_color.getText());
            stmt.setInt(4, (Integer) VehicleForm_Spinner_numWheels.getValue());
            stmt.setInt(5, (Integer) VehicleForm_Spinner_numDoors.getValue());
            stmt.setString(6, VehicleForm_TextInput_transmition.getText());
            stmt.setInt(7, (Integer) VehicleForm_Spinner_price.getValue());
            stmt.setString(8,VehicleForm_ComboBox_fueltype.getSelectedItem().toString());
            stmt.setInt(9, (Integer) VehicleForm_Spinner_horsePower.getValue());
            stmt.execute();
            stmt.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Dialog", JOptionPane.ERROR_MESSAGE);
        }
        
       
    }//GEN-LAST:event_VehicleForm_Button_addActionPerformed

    private void EmployeeForm_Button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeForm_Button_addActionPerformed
        try{
            if(!EmployeeForm_TextInput_password.getText().equals(EmployeeForm_TextInput_confirmPassword.getText())){
                JOptionPane.showMessageDialog(this, "Password tidak sama", "Dialog", JOptionPane.ERROR_MESSAGE);
            }else{
                Date date = new SimpleDateFormat("dd/MM/yyyy").parse(EmployeeForm_ComboBox_dd.getSelectedItem().toString()+"/"+
                        EmployeeForm_ComboBox_mm.getSelectedItem().toString()+"/"+
                        EmployeeForm_ComboBox_yyyy.getSelectedItem().toString());
                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                
                stmt = conn.prepareStatement("INSERT INTO employee(username, password, name, position, birth_date, gender) VALUES(?,?,?,?,?,?)");
                stmt.setString(1, EmployeeForm_TextInput_username.getText());
                stmt.setString(2, EmployeeForm_TextInput_password.getText());
                stmt.setString(3, EmployeeForm_TextInput_name.getText());
                stmt.setString(4, EmployeePosition.getSelection().getActionCommand());
                stmt.setDate(5, sqlDate);
                stmt.setString(6, EmployeeGender.getSelection().getActionCommand());
                stmt.execute();
                stmt.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Dialog", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EmployeeForm_Button_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JButton AddEmployeeButton;
    private javax.swing.JButton AddVehicleButton;
    private javax.swing.JLayeredPane ContentPanel;
    private javax.swing.JPanel CustomerFormPanel;
    private javax.swing.JButton CustomerForm_Button_add;
    private javax.swing.JButton CustomerForm_Button_add1;
    private javax.swing.JLabel CustomerForm_Label_address;
    private javax.swing.JLabel CustomerForm_Label_address1;
    private javax.swing.JLabel CustomerForm_Label_gender;
    private javax.swing.JLabel CustomerForm_Label_gender1;
    private javax.swing.JLabel CustomerForm_Label_name;
    private javax.swing.JLabel CustomerForm_Label_name1;
    private javax.swing.JLabel CustomerForm_Label_phoneNumber;
    private javax.swing.JLabel CustomerForm_Label_phoneNumber1;
    private javax.swing.JRadioButton CustomerForm_RB_Female;
    private javax.swing.JRadioButton CustomerForm_RB_Female1;
    private javax.swing.JRadioButton CustomerForm_RB_Male;
    private javax.swing.JRadioButton CustomerForm_RB_Male1;
    private javax.swing.JTextField CustomerForm_TextInput_address;
    private javax.swing.JTextField CustomerForm_TextInput_address1;
    private javax.swing.JTextField CustomerForm_TextInput_name;
    private javax.swing.JTextField CustomerForm_TextInput_name1;
    private javax.swing.JTextField CustomerForm_TextInput_phoneNumber;
    private javax.swing.JTextField CustomerForm_TextInput_phoneNumber1;
    private javax.swing.ButtonGroup CustomerGender;
    private javax.swing.JPanel CustomerPageContentPanel;
    private javax.swing.JPanel Customer_PanelButton;
    private javax.swing.JPanel EmployeeFormPanel;
    private javax.swing.JButton EmployeeForm_Button_add;
    private javax.swing.JComboBox<String> EmployeeForm_ComboBox_dd;
    private javax.swing.JComboBox<String> EmployeeForm_ComboBox_mm;
    private javax.swing.JComboBox<String> EmployeeForm_ComboBox_yyyy;
    private javax.swing.JLabel EmployeeForm_Label_birthdate;
    private javax.swing.JLabel EmployeeForm_Label_confirmPassword;
    private javax.swing.JLabel EmployeeForm_Label_gender;
    private javax.swing.JLabel EmployeeForm_Label_name;
    private javax.swing.JLabel EmployeeForm_Label_password;
    private javax.swing.JLabel EmployeeForm_Label_position;
    private javax.swing.JLabel EmployeeForm_Label_username;
    private javax.swing.JRadioButton EmployeeForm_RB_Female;
    private javax.swing.JRadioButton EmployeeForm_RB_Male;
    private javax.swing.JRadioButton EmployeeForm_RB_Manager;
    private javax.swing.JRadioButton EmployeeForm_RB_Sales;
    private javax.swing.JRadioButton EmployeeForm_RB_Technician;
    private javax.swing.JTextField EmployeeForm_TextInput_confirmPassword;
    private javax.swing.JTextField EmployeeForm_TextInput_name;
    private javax.swing.JTextField EmployeeForm_TextInput_password;
    private javax.swing.JTextField EmployeeForm_TextInput_username;
    private javax.swing.ButtonGroup EmployeeGender;
    private javax.swing.JPanel EmployeePageContentPanel;
    private javax.swing.ButtonGroup EmployeePosition;
    private javax.swing.JPanel Employee_PanelButton;
    private javax.swing.JPanel HomePageContentPanel;
    private javax.swing.JPanel Home_PanelButton;
    private javax.swing.JPanel Parts_PanelButton;
    private javax.swing.JPanel VehicleFormPanel;
    private javax.swing.JButton VehicleForm_Button_add;
    private javax.swing.JButton VehicleForm_Button_add1;
    private javax.swing.JComboBox<String> VehicleForm_ComboBox_fueltype;
    private javax.swing.JComboBox<String> VehicleForm_ComboBox_fueltype1;
    private javax.swing.JLabel VehicleForm_Label_brand;
    private javax.swing.JLabel VehicleForm_Label_brand1;
    private javax.swing.JLabel VehicleForm_Label_color;
    private javax.swing.JLabel VehicleForm_Label_color1;
    private javax.swing.JLabel VehicleForm_Label_fueltype;
    private javax.swing.JLabel VehicleForm_Label_fueltype1;
    private javax.swing.JLabel VehicleForm_Label_horsePower;
    private javax.swing.JLabel VehicleForm_Label_horsePower1;
    private javax.swing.JLabel VehicleForm_Label_name;
    private javax.swing.JLabel VehicleForm_Label_name1;
    private javax.swing.JLabel VehicleForm_Label_numDoors;
    private javax.swing.JLabel VehicleForm_Label_numDoors1;
    private javax.swing.JLabel VehicleForm_Label_numWheels;
    private javax.swing.JLabel VehicleForm_Label_numWheels1;
    private javax.swing.JLabel VehicleForm_Label_price;
    private javax.swing.JLabel VehicleForm_Label_price1;
    private javax.swing.JLabel VehicleForm_Label_transmition;
    private javax.swing.JLabel VehicleForm_Label_transmition1;
    private javax.swing.JLabel VehicleForm_Label_weight;
    private javax.swing.JLabel VehicleForm_Label_weight1;
    private javax.swing.JSpinner VehicleForm_Spinner_horsePower;
    private javax.swing.JSpinner VehicleForm_Spinner_horsePower1;
    private javax.swing.JSpinner VehicleForm_Spinner_numDoors;
    private javax.swing.JSpinner VehicleForm_Spinner_numDoors1;
    private javax.swing.JSpinner VehicleForm_Spinner_numWeight;
    private javax.swing.JSpinner VehicleForm_Spinner_numWeight1;
    private javax.swing.JSpinner VehicleForm_Spinner_numWheels;
    private javax.swing.JSpinner VehicleForm_Spinner_numWheels1;
    private javax.swing.JSpinner VehicleForm_Spinner_price;
    private javax.swing.JSpinner VehicleForm_Spinner_price1;
    private javax.swing.JTextField VehicleForm_TextInput_brand;
    private javax.swing.JTextField VehicleForm_TextInput_brand1;
    private javax.swing.JTextField VehicleForm_TextInput_color;
    private javax.swing.JTextField VehicleForm_TextInput_color1;
    private javax.swing.JTextField VehicleForm_TextInput_name;
    private javax.swing.JTextField VehicleForm_TextInput_name1;
    private javax.swing.JTextField VehicleForm_TextInput_transmition;
    private javax.swing.JTextField VehicleForm_TextInput_transmition1;
    private javax.swing.JPanel VehiclePageContentPanel;
    private javax.swing.JPanel Vehicle_PanelButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel loggedUserLabel;
    // End of variables declaration//GEN-END:variables
}
